version: '3.8'

services:
  dev-server:
    build: .
    container_name: ai-dev-workflow
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
